# 运行模式(debug:调试,release:正式,test:测试)
run_mode = "test"

# casbin模型配置文件(也可以启动服务时使用-m指定)
casbin_model = "config/model.conf"

# http监听地址
http_host = "0.0.0.0"

# http监听端口
http_port = 8086

# 静态站点目录(也可以启动服务时使用-www指定)
www = ""

# 系统唯一标识
system_identify = "rbac"

# 系统root用户名
system_root_user = "root"

# 系统root密码
system_root_password = "123"

# 数据库存储(目前支持的存储：gorm)
db_store = "gorm"

# 认证模式(支持的认证模式：session)
auth_mode = "session"

# 会话配置
[session]
# 存储在header中的cookie标识
header_name = "access-token"
# 会话签名
sign = "GINADMIN"
# 会话过期时长(单位秒)
expired = 7200
# 是否启用写入存储（如果启用存储，则使用当前db的存储类型；否则默认使用内存存储）
enable_store = true

# 日志配置
[log]
# 日志级别(2:error,3:warn,4:info,5:debug)
level = 5
# 日志格式（text/json）
format = "text"
# 是否启用日志钩子(如果启用钩子，则使用当前db的存储类型；否则不写入钩子)
enable_hook = true
# 写入钩子的最大工作线程数量
hook_max_thread = 2
# 写入钩子的最大缓冲区数量
hook_max_buffer = 512

[gorm]
# 是否开启调试模式
debug = true
# 存储类型(目前支持的存储：mysql/sqlite3/postgres)
store_type = "mysql"
# 设置连接可以被重新使用的最大时间量(单位：秒)
max_lifetime = 7200
# 设置打开连接到数据库的最大数量
max_open_conns = 150
# 设置空闲连接池中的最大连接数
max_idle_conns = 50
# 表名前缀
table_prefix = "g"

[mysql]
# 连接地址
host = "127.0.0.1"
# 连接端口
port= 3306
# 用户名
user = "root"
# 密码
password = "123456"
# 数据库
dbname = "ginadmin"

[sqlite3]
db_path = "data/ginadmin.db"

[postgres]
# 连接地址
host = "127.0.0.1"
# 连接端口
port= 5432
# 用户名
user = "root"
# 密码
password = "123456"
# 数据库
dbname = "ginadmin"
