# 运行模式(debug:调试,test:测试,release:正式)
run_mode = "debug"

# casbin模型配置文件(也可以启动服务时使用-m指定)
casbin_model_conf = ""

# 静态站点目录(也可以启动服务时使用-www指定)
www = ""

# swagger文档目录(也可以启动服务时使用-swagger指定)
swagger = ""

# 存储模式(支持：gorm)
db_mode = "gorm"

# 用户授权模式(支持：session/jwt)
auth_mode = "jwt"

# 是否允许动态创建资源数据
allow_create_resources = true

# 是否允许初始化菜单数据
allow_initialize_menus = true

# http配置
[http]
# http监听地址
host = "0.0.0.0"
# http监听端口
port = 8086
# http优雅关闭等待超时时长(单位秒)
shutdown_timeout = 10

# root用户
[root_user]
# 登录用户名
user_name = "root"
# 登录密码
password = "123"
# 显示的真实姓名
real_name = "超级用户"

# 图形验证码
[captcha]
# 存储方式(支持：memory/redis)
store = "memory"
# 数字长度
length = 4
# 图片宽度
width = 100
# 图片高度
height = 45
# redis数据库(如果存储方式是redis，则指定存储的数据库)
redis_db = 10

# 请求频率限制(如果redis可用则使用redis，否则使用内存存储)
[rate_limiter]
# 是否启用
enable = true
# 每分钟每个用户允许的最大请求数量
count = 300
# redis数据库(如果存储方式是redis，则指定存储的数据库)
redis_db = 11

# 跨域请求
[cors]
# 是否启用
enable = true
# 允许跨域请求的域名列表(*表示全部允许)
allow_origins = ["*"]
# 允许跨域请求的请求方式列表
allow_methods = ["GET","POST","PUT","DELETE","PATCH"]
# 允许客户端与跨域请求一起使用的非简单标头的列表
allow_headers = []
# 请求是否可以包含cookie，HTTP身份验证或客户端SSL证书等用户凭据
allow_credentials = true
# 可以缓存预检请求结果的时间（以秒为单位）
max_age = 7200

# 会话配置
[session]
# 存储在header中的cookie标识
header_name = "Access-Token"
# 会话签名
sign = "GINADMIN"
# 会话过期时长(单位秒)
expired = 7200
# 是否启用写入存储（如果启用存储，则使用当前db的存储类型；否则默认使用内存存储）
enable_store = true

[jwt]
# 存储在header中的标识
header_name = "Access-Token"
# 秘钥
secret = "GINADMIN"
# 签名方式(支持的签名方式：HS256/HS384/HS512)
sign_method = "HS256"
# 过期时长(单位秒)
expired = 7200

# 日志配置
[log]
# 日志级别(1:fatal 2:error,3:warn,4:info,5:debug)
level = 5
# 日志格式（text/json）
format = "text"
# 是否启用日志钩子(如果启用钩子，则使用当前db的存储类型；否则不写入钩子)
enable_hook = true
# 写入钩子的最大工作线程数量
hook_max_thread = 1
# 写入钩子的最大缓冲区数量
hook_max_buffer = 512

# redis配置
[redis]
# 地址
addr = "192.168.33.90:6379"
# 密码
password = ""

# gorm配置
[gorm]
# 是否开启调试模式
debug = false
# 数据库类型(目前支持的数据库类型：mysql/sqlite3/postgres)
db_type = "mysql"
# 设置连接可以重用的最长时间(单位：秒)
max_lifetime = 7200
# 设置数据库的最大打开连接数
max_open_conns = 150
# 设置空闲连接池中的最大连接数
max_idle_conns = 50
# 数据库表名前缀
table_prefix = "g_"

# mysql数据库配置
[mysql]
# 连接地址
host = "127.0.0.1"
# 连接端口
port= 3306
# 用户名
user = "root"
# 密码
password = "123456"
# 数据库
db_name = "gadmin"
# 连接参数
parameters = "charset=utf8&parseTime=True&loc=Local&allowNativePasswords=true"

# postgres数据库配置
[postgres]
# 连接地址
host = "127.0.0.1"
# 连接端口
port= 5432
# 用户名
user = "root"
# 密码
password = "123456"
# 数据库
db_name = "gadmin"

# sqlite数据库配置
[sqlite3]
# 数据库路径
path = "data/gadmin.db"
